import image1 from "../../assets/Saved Pictures/13 Smart Posing Tips to Capture Perfect Male Portrait Photographs For 2023.jpeg";
import image2 from "../../assets/Saved Pictures/5 Tricks To Enhance The Basic Tee.jpeg";
import image3 from "../../assets/Saved Pictures/_Unleash Your Style_ Men's Street Outfits for Urban Trendsetters_.jpeg";
import image4 from "../../assetS/Saved Pictures/Classic and minimalist style.jpeg";
import image5 from "../../assets/Saved Pictures/Clothing You Should Stop Wearing Aged 40+.jpeg";
import image6 from "../../assets/Saved Pictures/How To Style Casual Outfit For Guys Like A Pro!.jpeg";
import image7 from "../../assets/Saved Pictures/Jeans Fashion Glossary.jpeg";
import image8 from "../../assets/Saved Pictures/Loose Urban Style For Lazy Weekends.jpeg";
import image9 from "../../assets/Saved Pictures/Male Fashion Trends.jpeg";
import image11 from "../../assets/Saved Pictures/STYLEGUISE.jpeg";
import image12 from "../../assets/Saved Pictures/Tommy Hilfiger Men's Core Stretch Slim Poplin Shirt Casual, Midnight Blue, Medium.jpeg";
import image13 from "../../assets/Saved Pictures/Urban Explorer_ City-Inspired Clothing.jpeg";
import image14 from "../../assets/Saved Pictures/토모나리(TOMONARI) [11컬러 베이직 오픈 셔츠].jpeg";

const collectData = [
  {
    id: 1,
    ima: image1,
  },
  {
    id: 2,
    ima: image2,
  },
  {
    id: 3,
    ima: image3,
  },
  {
    id: 4,
    ima: image4,
  },
  {
    id: 5,
    ima: image5,
  },
  {
    id: 6,
    ima: image6,
  },
  {
    id: 7,
    ima: image7,
  },
  {
    id: 8,
    ima: image8,
  },
  {
    id: 9,
    ima: image9,
  },
  {
    id: 11,
    ima: image11,
  },
  {
    id: 12,
    ima: image12,
  },
  {
    id: 13,
    ima: image13,
  },
  {
    id: 14,
    ima: image14,
  },
];
export default collectData;
